# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 11"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"  
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{images,js,scss}/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "src/templates/components"
  appSass:
    - "src/assets/scss/app.scss"

  #Paths to lint report folder
  sasslint: "reports/sass-lint.html"
  jslint: "reports/js-lint.html"
